#!/bin/zsh

echo "Windows Registry Editor Version 5.00\r" > backup.reg

for i (*/*.reg) {
    cat $i | iconv -f utf-16 -t utf-8 -c | sed 1d >> backup.reg
}

echo "Windows Registry Editor Version 5.00\r" > delete.reg

cat backup.reg | grep '\[' | sed 's/^\[/\r\n\[-/g' >> delete.reg

# cat backup.reg | sed 's/\([^=]*=\).*/\1-\r/g' | sed '/^  /d' > delete.reg
