#!/bin/zsh

(($#* >= 2)) || {
    echo Usage: $0 target files/dirs
    return 1
}

case $1 {
    (*.zip|*.7z|*.jar)
    7z a $1 $*[2,-1]
    ;;

    (*.tar|*.tgz|*.txz|*.tbz2|*.tlz|*.tar.*)
    tar -cavf $1 $*[2,-1]
    ;;

    (*.gz)
    gzip -cv $*[2,-1] > $1
    ;;

    (*.xz)
    xz -cv $*[2,-1] > $1
    ;;

    (*.bz2)
    bzip2 -cv $*[2,-1] > $1
    ;;

    (*.lzma)
    lzma -cv $*[2,-1] > $1
    ;;

    (*.lz4)
    lz4 -cv $2 > $1
    ;;

    (*.ar)
    ar r $1 $*[2,-1]
    ;;
}
