#!/bin/zsh

. ~/.zshrc

# JPG 作为中间扩展名
rename .JPG .jpg **/*.JPG

rr -j 20

for i (**/*.(jpg|png|PNG|jpeg|JPEG)) {
    rr gm convert $i $i.JPG
}

# 等所有操作结束
wait

# 删除原文件
rm -f **/*.(jpg|png|PNG|jpeg|JPEG)

# 避免覆盖同名文件
rename .jpg.JPG .jpg **/*.JPG
rename .png.JPG _p.jpg **/*.JPG
rename .PNG.JPG _p.jpg **/*.JPG
rename .jpeg.JPG _e.jpg **/*.JPG
rename .JPEG.JPG _e.jpg **/*.JPG
