#!/usr/bin/python
# -*- coding:utf-8 -*-

import xmlrpc.client

server = xmlrpc.client.ServerProxy('http://192.168.1.6:6800/rpc')
result = server.aria2.tellStopped(0, 10000)

for i in result:
    if i['errorCode'] == '0':
        print('Remove ' + i['gid'] + ' ' + i['files'][0]['path'])
        print(server.aria2.removeDownloadResult(i['gid']))
    else:
        # from pprint import pprint
        # pprint(i)
        print(i['errorCode'] + ':' + i['errorMessage'])
        print(i['gid'] + ' ' + i['files'][0]['path'])
