#!/bin/bash

rm -rf VimDesktop*
mkdir VimDesktop

cp * VimDesktop -r 2>/dev/null
rm VimDesktop/vimd.ini
rm -rf VimDesktop/VimDesktop
rm -rf VimDesktop/doc/vimdesktop.wiki/.git

apack VimDesktop-$1.zip VimDesktop
rm -rf VimDesktop
mv VimDesktop-$1.zip ~/tmp
cp doc/vimdesktop.wiki/HISTORY.md ~/tmp/VimDesktop更新历史.txt
