#!/bin/bash

cg=/tmp/.cg
touch $cg

if [ $# -gt 0 ]; then
    echo $PWD > $cg
    name="$1"

    if [ $(expr substr "$1" 1 1) = '-' ]; then
        name=$2
        if [ $# = 2 ]; then
            flag1='-r'
            flag2='.'
        fi
    fi

    echo $name >> $cg

    if [ $# = 1 ]; then
        flag1='-r'
        flag2='.'
    fi

    grep -EHn "$@" $flag1 $flag2 --color=yes \
        --exclude-dir='.svn' --exclude-dir='.git' --exclude-dir='.libs' \
        --exclude=tags \
        | nl  -n ln >> $cg
fi

cat $cg 
