#!/bin/zsh

# Remove locale files and docs
rm -rvf /usr/share/locale/*
rm -rvf /usr/share/man/^man*
rm -rvf /usr/share/info/*
rm -rvf /usr/share/doc/*
rm -rvf /usr/share/vim/vim80/{doc,lang,tutor,spell}
rm -rvf /usr/share/gtk-doc

# Remove python useless files
rm -rvf /usr/lib/python3.6/test
rm -rvf /usr/lib/python3.6/**/*.a
rm -rvf /usr/lib/python2.7/test
rm -rvf /usr/lib/python2.7/**/*.pyo
rm -rvf /usr/lib/python2.7/**/*.a

# Remove perl all files
rm -rvf /etc/profile.d/perl*
rm -rvf /usr/bin/core_perl
rm -rvf /usr/bin/perl
rm -rvf /usr/bin/site_perl
rm -rvf /usr/bin/vendor_perl
rm -rvf /usr/lib/perl5
rm -rvf /usr/share/fish
rm -rvf /usr/share/makepkg-template/perl*
rmdir /usr/share/makepkg-template
rm -rvf /usr/share/man/man*/*perl*
rm -rvf /usr/share/perl5
rm -rvf /usr/share/man/*/*.3pm.*

# Remove other useless files
rm -rvf /usr/lib/libgo.so*
rm -rvf /usr/lib/xorg/modules/dri/*
rm -rvf /usr/lib/guile/2.2
