#!/bin/bash

for i in $(awk '{print $1}' /etc/setup/installed.db); do
    apt-cyg show "^$i$" | grep "requires:" >> requires.txt
done

for i in $(awk '{print $1}' /etc/setup/installed.db); do
    grep $i requires.txt >/dev/null || echo $i
done

rm requires.txt
