#!/usr/bin/env python2.7

"""
http://tieba.baidu.com/p/3967366107
http://pan.baidu.com/s/1mghAyEW
"""

import urllib2, urllib
import json
import zlib

class FanyiError(Exception):
	pass

def fanyi(sentence):

	if any(True for i in str(sentence) if i > '\x7f'):
		trans_type = 'ZH_CN2EN'
	else:
		trans_type = 'EN2ZH_CN'

	url = 'http://fanyi.youdao.com/translate?'
	param = (('smartresult', 'dict'),
				('smartresult', 'rule'), 
				('smartresult', 'ugc'))
	query = {'type': trans_type, 'i': sentence, 
			'doctype':'json', 'xmlVersion':'1.6',
			'keyfrom':'fanyi.web', 'ue':'UTF-8', 
			'typoResult':'true', 'flag':'false'}

	req = urllib2.Request(
			url+urllib.urlencode(param),
			urllib.urlencode(query)
			)

	req.add_header('connection', 'close')
	#req.add_header('content-type', 'application/x-www-form-urlencoded; charset=utf-8')
	req.add_header('accept', '*/*')
	req.add_header('accept-charset', 'utf-8')
	req.add_header('accept-encoding', 'gzip,deflate')
	req.add_header('accept-language', 'en;q=0.8,en-US;q=0.6,en;q=0.4')
	req.add_header('user-agent', 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)')
	req.add_header('host', 'fanyi.youdao.com')

	respData = urllib2.urlopen(req).read()

	result = zlib.decompress(respData, zlib.MAX_WBITS|16)

	try:
		data = json.loads(result)
	except ValueError:
		raise FanyiError('invalid input')

	if data['errorCode'] == 0:
		try:
			return data['translateResult'][0][0]['tgt']
		except IndexError, KeyError:
			raise FanyiError('no result')
	else:
		raise FanyiError('non zero error code')

if __name__ == '__main__':
	import sys
	try:
		if len(sys.argv) > 1:
			print fanyi(' '.join(sys.argv[1:])).encode('utf-8')
		else:
			print fanyi(sys.stdin.read()).encode('utf-8')
	except FanyiError:
		pass
