#!/bin/zsh

print -Pn "\e]0;goreliu\a"
preexec() {}

pgrep tmux > /dev/null

if [ $? -eq 0 ]; then
    tmux a
else
    tmux
fi

pgrep tmux > /dev/null || rm /tmp/tmux-*/default 2> /dev/null

# tmux a &>/dev/null || tmux
