#!/bin/bash

[ $# -eq 2 ] || {
    echo "Usage: $0 category filename.md"
    exit 1
}

category="$1"
filename="$2"

cp "$filename" "$HOME/TranslateProject/translated/$category/"

cd ~/TranslateProject
git add "translated/$category/$filename"
git rm "sources/$category/$filename"
git ci -m "[Translated] $filename"
git push
