#!/bin/bash

filename="$1"

sed -i 's/译者ID/goreliu/g' "$filename"
cp "$filename" "$HOME/mine/doc/blog/TranslateProject/"
sed -i 1i'Translating by goreliu ...\n' "$filename"

git ci -m "[Translating] $filename"
git push
cd ../../
hub pull-request
