#!/bin/bash

source ~/.uuaprc

# UUAP_USERNAME="__YOURNAME__"
# UUAP_PASSWORD="__YOURPASSWORD__"
# UUAP_COOKIEJAR="$HOME/.uuap_cookie"

UUAP_CURL="curl -s -b $UUAP_COOKIEJAR -c $UUAP_COOKIEJAR -i -A 'BaiduUUAPLoginBot/1.0'"

$UUAP_CURL uuap.baidu.com/login | \
    perl -ne '($name, $value) = /input\s+type="hidden"\s+name="([^"]+)"\s+value="([^"]+)"/; print "$name=$value&" if ($name && $value)' | \
    xargs -l -i echo {}username=$UUAP_USERNAME'&'password=$UUAP_PASSWORD | \
    xargs -l -i $UUAP_CURL -d "{}" uuap.baidu.com/login &>/dev/null

#$UUAP_CURL 'noah.baidu.com/olive/index.php?r=Passport/logging/Index' &>/tmp/login-noah.log
