#!/bin/bash

kill $(ps aux | awk '/[^]] mplayer -playlist /{print $2}')
ls > .tmplist
n=$(sed -n /${1/*\//}/= .tmplist)
line=`cat .tmplist | wc -l`
tail -n $((line-n+1)) .tmplist > /tmp/.tmplist
head -n $((n-1)) .tmplist >> /tmp/.tmplist
mv /tmp/.tmplist .tmplist

(mplayer -playlist .tmplist -quiet -loop 0 && sleep 1 && rm .tmplist) &
