#!/bin/bash

result="$(readlink -f $PWD)"

[ -n "$1" ] && result="$(readlink -f $1)"

if [ "${result:0:5}" = "/mnt/" ]; then
	echo "${result:5:1}:${result:6}"
else
	echo "$(echo c:/Users/goreliu/AppData/Local/lxss/rootfs$result \
		| sed 's|rootfs/home|home|g')"
fi
