#!/bin/zsh

in_file=$1
time_file=$2
out_file=$1.out.mp4

index=1
while {read s_time e_time} {
    integer s_ms=0
    integer e_ms=0

    if [[ $s_time != *.* ]] {
        s_time=$s_time.000
    }

    if [[ $e_time != *.* ]] {
        e_time=$e_time.000
    }

    if [[ $#s_time == 6 ]] {
        s_time=00:00:$s_time
    } elif [[ $#s_time == 9 ]] {
        s_time=00:$s_time
    }

    if [[ $#e_time == 6 ]] {
        e_time=00:00:$e_time
    } elif [[ $#e_time == 9 ]] {
        e_time=00:$e_time
    }

    s_s=$(date +%s -d$s_time[1,-5])
    e_s=$(date +%s -d$e_time[1,-5])

    ((s_ms += s_s * 1000))
    ((e_ms += e_s * 1000))

    local duration=$(((e_ms - s_ms) / 1000)).$(((e_ms - s_ms) % 1000))

    ffmpeg -hide_banner -ss $s_time -t $duration -i $in_file -acodec copy -vcodec copy $index.tmp.mp4 </dev/null
    ((index++))
} < $time_file

ffmpeg -hide_banner -f concat -i input_list -c copy $out_file

rm input_list *.tmp.mp4
