#!/bin/zsh

in_file=$1
in_file_ext=${1:e}
time_file=$2
out_file=$1.out.mp4
echo -n > input_list

if [[ $3 != "-c" && $in_file_ext != rm* ]] {
    convert_opts=(-acodec copy -vcodec copy)
}

index=1
while {read s_time e_time} {
    integer s_ms
    integer e_ms

    if [[ s_time != *:* ]] {
        ((s_ms = s_time * 1000))
    } else {
        if [[ $s_time != *.* ]] {
            s_time=$s_time.000
        }

        if [[ $#s_time == 6 ]] {
            s_time=00:00:$s_time
        } elif [[ $#s_time == 9 ]] {
            s_time=00:$s_time
        }

        s_s=$(date +%s -d$s_time[1,-5])
        s_ms=$s_time[-3,-1]

        ((s_ms += s_s * 1000))
    }

    if [[ e_time != *:* ]] {
        ((e_ms = e_time * 1000))
    } else {
        if [[ $e_time != *.* ]] {
            e_time=$e_time.000
        }

        if [[ $#e_time == 6 ]] {
            e_time=00:00:$e_time
        } elif [[ $#e_time == 9 ]] {
            e_time=00:$e_time
        }

        e_s=$(date +%s -d$e_time[1,-5])
        e_ms=$e_time[-3,-1]

        ((s_ms += s_s * 1000))
    }

    local duration=$(((e_ms - s_ms) / 1000)).$(((e_ms - s_ms) % 1000))

    echo "file '"$index".tmp.mp4'" >> input_list
    ffmpeg -hide_banner -ss $s_time -t $duration -i $in_file $convert_opts $index.tmp.mp4 </dev/null
    ((index++))
} < $time_file

if ((index > 2)) {
    ffmpeg -hide_banner -f concat -i input_list -c copy $out_file
} else {
    mv 1.tmp.mp4 $out_file
    touch 1.tmp.mp4
}

if [[ $3 != "-d" ]] {
    rm -f input_list *.tmp.mp4 cut_run.sh
}
