#!/bin/bash
cat > $1.html << EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>New</title>
</head>

<body>
EOF

markdown_py $1 -f $1.tmp.html
cat $1.tmp.html >> $1.html

cat >> $1.html << EOF
</body>
</html>
EOF

wkhtmltopdf $1.html $1.pdf
rm $1.html $1.tmp.html
