#!/bin/bash
for i in \
    .adobe\
    .dbus\
    .gstreamer-0.10\
    .juniper_networks\
    .kchmviewer\
    .local\
    .macromedia\
    .pulse\
    .w3m\
; do
    rm -r $i
    ln -s .cache $i
done
