#!/bin/bash

[ -e ~/.cache/msys.db.txt ] && {
    [ $(($(date +%s) - $(stat -c%Y ~/.cache/msys.db.txt 2>/dev/null))) -ge 86400 ] && {
        rm ~/.cache/msys.db.txt
    }
}

[ -e ~/.cache/msys.db.txt ] || {
    curl http://repo.msys2.org/msys/x86_64/msys.db.tar.gz | tar -tz > ~/.cache/msys.db.txt
}

[ -n "$1" ] && {
    cat ~/.cache/msys.db.txt | grep -v /desc | grep -E "$@"
    exit
}

cat ~/.cache/msys.db.txt | grep -v /desc | grep -E '(msys2-runtime-2|openssh|mintty)'
