#!/bin/bash

[ "$OSTYPE" = "msys" ] && {
    cd
    update_msys2_mirrorlist
    mkpasswd | sed 's/bash/zsh/g' > /etc/passwd
    mkgroup > /etc/group
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/localtime
    ln -sf c:/Windows/System32/drivers/etc/hosts /etc/hosts
    ln -f "$HOME/.vimperatorrc" c:/Users/goreliu/.vimperatorrc
    ln -sf /c/mine /
}

[ "$OSTYPE" = "linux-gnu" ] && {
    cd /etc
    sudo ln -sf ../usr/share/zoneinfo/Asia/Shanghai localtime

    [ -e /etc/hostname ] || {
        sudo sh -c 'echo my-pc-linux > /etc/hostname'
    }

    grep '#zh_CN.UTF-8 UTF-8' /etc/locale.gen >/dev/null && {
        sudo sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
        sudo sed -i 's/#zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/g' /etc/locale.gen
        sudo locale-gen
    }
}
