#!/bin/zsh

if [[ $1 == http || $1 = www* ]] {
    z start "" $*
    return
}

dir_name=${1:h}
file_name=${1:t}

if [[ $dir_name == / ]] {
    cd /; setsid z start .
} elif [[ $dir_name == /mnt ]] {
    cd /; setsid z start "" $file_name:
} else {
    shift 2>/dev/null
    cd $dir_name && setsid z start "" $file_name $*
}
