#!/bin/bash

[ "${1:0:4}" = "http" -o "${1:0:4}" = "www." ] && {
    /init cmd /C start "$@"
    exit
}

dir_name="$(dirname "$1")"
base_name="$(basename "$1")"

if [ "$dir_name" = "/" ]; then
    (cd /; z start . &)
elif [ "$dir_name" = "/mnt" ]; then
    (cd /; z start "$base_name:" &)
else
    shift 2>/dev/null
    (cd "$dir_name" && z start "$base_name" "$@" &)
fi
