#!/bin/bash

function f() {
    $1 "$2" &>/dev/null &
}

if [ $# == 0 ]; then
    exit
fi

if [ "${1/:*/}" = 'http' ] || [ "${1/:*/}" = 'https' ]; then
    f chromium "$1"
    exit
fi

if [ "${1/:*/}" = 'ftp' ]; then
    lftp "$1"
    exit
fi

declare -l p=${1/*./}

case $p in
    pdf)
        f zathura "$1"
        ;;
    chm)
        f kchmviewer "$1"
        ;;
    html|htm|mht|mhtml|swf)
        f chromium "$1"
        ;;
    doc|docx|ppt|pptx|xls|xlsx)
        f libreoffice "$1"
        ;;
    jpg|png|gif)
        f geeqie "$1"
        ;;
    avi|mp4|mp3|aac|ogg|ogv|mts|mkv|asf|wmv|flv|f4v|dat|vob|iso|ts|rm|rmvb|m4v|3gp|mpg)
        mplayer "$1"
        ;;
    sqlite)
        f sqlitebrowser "$1"
        ;;
    *)
        vim "$1"
        ;;
esac
