#!/bin/bash

[ "$HOSTNAME" = "my-pc" ] && {
    if [ $# = 0 ]; then
        z shutdown -s -t 0
    elif [ $1 = 1 ]; then
        z shutdown -r -t 0
    fi
    exit
}

type systemctl &>/dev/null && {
    if [ $# = 0 ]; then
        sudo systemctl poweroff
    elif [ $1 = 1 ]; then
        sudo systemctl reboot
    fi
    exit
}
