#!/bin/bash

[ "$HOSTNAME" = "MY-PC" ] && {
    if [ $# = 0 ]; then
        wrun shutdown -s -t 0
    elif [ $1 = 1 ]; then
        wrun shutdown -r -t 0
    fi
    exit
}

type shutdown &>/dev/null && {
    if [ $# = 0 ]; then
        shutdown -s -t 0
    elif [ $1 = 1 ]; then
        shutdown -r -t 0
    fi
    exit
}

type systemctl &>/dev/null && {
    if [ $# = 0 ]; then
        sudo systemctl poweroff
    elif [ $1 = 1 ]; then
        sudo systemctl reboot
    fi
    exit
}
