#!/bin/bash

type shutdown >/dev/null && {
    if [ $# = 0 ]; then
        shutdown -s -t 0
    elif [ $1 = 1 ]; then
        shutdown -r -t 0
    fi
}

type systemctl >/dev/null && {
    if [ $# = 0 ]; then
        sudo systemctl poweroff
    elif [ $1 = 1 ]; then
        sudo systemctl reboot
    fi
}
