#!/bin/zsh

(( $+1 )) || {
    echo 'Usage: renamex "s/aaa/bbb/g" *.txt'
    return
}

for i in "$@[2,-1]"; {
    local new_name="$(echo "$i" | sed "$1")"
    [[ "$i" == "$new_name" ]] && continue
    echo "Renaming $i to $new_name ..."
    mv "$i" "$new_name"
}
