#!/bin/zsh

# A simple tool to remove duplicate files.

autoload -U zargs

local files=("${(f)$(zargs **/*(.) -- md5sum)}")
local files_d=()
typeset -A md5s

for i in $files; {
    local md5=$i[1,32]

    if (( $+md5s[$md5] )) {
        files_d+=($i[35,-1])
    } else {
        md5s[$md5]=1
    }
}

(( $#files_d )) && rm -v $files_d
