#!/bin/zsh
# A simple tool to remove duplicate files in the current directory and its subdirectories.

all=`mktemp -t XXXXX`
keep=`mktemp -t XXXXX`
find -type f | sort | sed 's/ /\\ /g' > $all
cat $all | xargs md5sum 2>/dev/null | sort | uniq -w32 \
	| sed -e 's/^[0-9a-f]\{32\} [ *]//g' -e 's/ /\\ /g' |sort >$keep
diff $all $keep | sed -e 's/^< \(\..*\)$/\1/g' -e 's/^[^\.].*$//g' | xargs rm -v 2>/dev/null

find -type d |sort -r |sed 's/ /\\ /g'|xargs rmdir 2>/dev/null

rm $all $keep
