#!/usr/bin/python
import socket,sys

if len(sys.argv) != 4:
    print('usage:\n    %s hostname port msg' % sys.argv[0])
    sys.exit(1)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((sys.argv[1], int(sys.argv[2])))
sock.send(bytes(sys.argv[3], encoding = 'utf-8'))
