#!/bin/bash

rsync -av --delete \
    --exclude git \
    --exclude tmp \
    --exclude .zhistory \
    --exclude .zhistory \
    --exclude .viminfo \
    --exclude .bash_history \
    /mnt/c/Users/goreliu/AppData/Local/lxss/home/goreliu /home
