#!/bin/bash

if [ $# = 0 ]; then
    word=`xclip -o`
else
    word="$*"
fi

w3m -dump -no-proxy "http://m.baidu.com/s?word=$word&ct_mark3=x" \
    | yad --text-info --center --width=600 --height=600 --title="$word"
