#!/bin/bash

if [ $# = 0 ]; then
    if [ -e "/dev/clipboard" ]; then
        word=`cat /dev/clipboard`
    else
        word=`xclip -o`
    fi
else
    word="$*"
fi

firefox "http://dict.youdao.com/search?q=$word"
