#!/bin/zsh

# 传入的参数
# 读文件前执行的语句
local begin_cmd
# 读文件后执行的语句
local end_cmd

# 供外部使用的变量
# 当前行内容，不含换行符
local l
# 当前行按照分隔符切分成的数组
local f
# 当前行号
local nr=1
# 当前行的列数
local nf

while {getopts F:f:B:b:E:e: arg} {
    case $arg {
        (F|f)
        IFS_BAK=$IFS
        IFS=$OPTARG
        ;;

        (B|b)
        begin_cmd=$OPTARG
        ;;

        (E|e)
        end_cmd=$OPTARG
        ;;
    }
}

eval $begin_cmd

while {read l} {
    f=(${=l})
    nf=$#f

    eval $*[-1]

    ((++nr))
}

eval $end_cmd

[[ -n $IFS_BAK ]] && IFS=$IFS_BAK
