#!/bin/zsh

# 传入的参数
# 读文件前执行的语句
local begin_cmd
# 读文件后执行的语句
local end_cmd
# 每行执行的语句
local cmd

# 供外部使用的变量
# 当前行内容，不含换行符
local l
# 当前行按照分隔符切分成的数组
local f
# 当前行号
local nr=1
# 当前行的列数
local nf

while {getopts f:b:e: arg} {
    case $arg {
        (f)
        local IFS=$OPTARG
        ;;

        (b)
        begin_cmd=$OPTARG
        ;;

        (e)
        end_cmd=$OPTARG
        ;;
    }
}

cmd=$*[-1]


eval $begin_cmd

while {read l} {
    f=(${=l})
    nf=$#f

    eval $cmd

    ((++nr))
}

eval $end_cmd
